# Конфигурационный файл для подключения плагина к базе данных
# Виды поддерживаемых баз данных: sqlite / mysql
language: ru_ru
database:
  type: sqlite
mysql:
  host: your-mysql-host
  port: 3306
  database: JClans-DataBase
  username: your-mysql-username
  password: your-mysql-password


