name: JClans
version: '${project.version}'
main: jcn.jclan.JClans
author: The_JCN
api-version: '1.20'
description: JClans - simple clan system for your minecraft server.
softdepend:
  - PlaceholderApi
  - LuckPerms
commands:
  clan:
    description: Основная команда плагина
  accept_delete_clan:
    description: Удаление клана
  decline_delete_clan:
    description: Отмена удаления клана
  accept_invite_in_clan:
    description: Принять заявку в клан
  decline_invite_in_clan:
    description: Отклонить заявку в клан
  c:
    description: Клановый чат
permissions:
  clan.member:
    default: not op