name: JClans
version: '${project.version}'
main: jcn.jclan.JClans
api-version: '1.20'
softdepend:
  - PlaceholderApi
  - LuckPerms
commands:
  clan:
    description: Основная команда плагина
  accept_delete_clan:
    description: Удаление клана
  decline_delete_clan:
    description: Отмена удаления клана
  accept_invite_in_clan:
    description: Принять заявку в клан
  decline_invite_in_clan:
    description: Отклонить заявку в клан
  c:
    description: Клановый чат